name: test11
description: dfghjkl111111111111111111111111111111112222222222222222222222222222333333333333333333
keywords:
  - websocket
  - network
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD
logo: http://img1.imgtn.bdimg.com/it/u=4289609089,1236661732&fm=26&gp=0.jpg

source_file:
  - src/*.c
  - src/*.S
  - ../*

build_config:
  include:
    - include/  
    - ../
    - ./
    
   include:
       - src/
   
  cflag: "zn  test $%^&*()  "                             # C 编译器所需要要的编译参数
  cflag: "test "  
  
  define:                                      # 宏定义
    - CONFIG_USING_TLS    NUM_ARGS
    - TEST!

  define:
      - TEST1
      - test2

install:
  - dest: include
    source:
      - "include/librws.h"
      - "test source"
